# Generated by Django 4.2.4 on 2023-09-01 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_image', models.ImageField(upload_to='productimg')),
                ('catagory', models.CharField(choices=[('iphone', 'iphone'), ('samsung', 'samsung'), ('sony', 'sony'), ('blackberry', 'blackberry'), ('LG', 'LG'), ('htc', 'htc'), ('motorola', 'motorola'), ('nokia', 'nokia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField(max_length=100)),
                ('discount_price', models.FloatField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
                ('catagory', models.CharField(choices=[('iphone', 'iphone'), ('samsung', 'samsung'), ('sony', 'sony'), ('blackberry', 'blackberry'), ('LG', 'LG'), ('htc', 'htc'), ('motorola', 'motorola'), ('nokia', 'nokia')], max_length=20)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('divisions', models.CharField(choices=[('DHAKA', 'DHAKA'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Barisal', 'Barisal'), ('sylhet', 'sylhet'), ('Mymansingh', 'Mymansingh'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna')], max_length=100)),
                ('districts', models.CharField(max_length=100)),
                ('thana', models.CharField(max_length=100)),
                ('villorroad', models.CharField(max_length=1000)),
                ('zipcode', models.IntegerField()),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField(max_length=100)),
                ('discount_price', models.FloatField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
                ('catagory', models.CharField(choices=[('shopproduct', 'shopproduct')], max_length=20)),
                ('product_image', models.ImageField(upload_to='productimg')),
                ('brand', models.CharField(choices=[('iphone', 'iphone'), ('samsung', 'samsung'), ('sony', 'sony'), ('blackberry', 'blackberry'), ('LG', 'LG'), ('htc', 'htc'), ('motorola', 'motorola'), ('nokia', 'nokia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyTopViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField(max_length=100)),
                ('discount_price', models.FloatField(max_length=100)),
                ('catagory', models.CharField(choices=[('iphone', 'iphone'), ('samsung', 'samsung'), ('sony', 'sony'), ('blackberry', 'blackberry'), ('LG', 'LG'), ('htc', 'htc'), ('motorola', 'motorola'), ('nokia', 'nokia')], max_length=20)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='TopNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField(max_length=100)),
                ('discount_price', models.FloatField(max_length=100)),
                ('catagory', models.CharField(choices=[('iphone', 'iphone'), ('samsung', 'samsung'), ('sony', 'sony'), ('blackberry', 'blackberry'), ('LG', 'LG'), ('htc', 'htc'), ('motorola', 'motorola'), ('nokia', 'nokia')], max_length=20)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='TopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField(max_length=100)),
                ('discount_price', models.FloatField(max_length=100)),
                ('catagory', models.CharField(choices=[('iphone', 'iphone'), ('samsung', 'samsung'), ('sony', 'sony'), ('blackberry', 'blackberry'), ('LG', 'LG'), ('htc', 'htc'), ('motorola', 'motorola'), ('nokia', 'nokia')], max_length=20)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Deliveres', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=45)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
